version: '3.8'

services:
  # Base image for development and production
  base:
    build:
      context: .
      dockerfile: docker/base.Dockerfile
    image: qredenceai/agenticfleet-base:latest
    profiles:
      - build-only

  # Development environment
  dev:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    image: qredenceai/agenticfleet-dev:latest
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    depends_on:
      - base
    command: chainlit run src/agentic_fleet/app.py --host 0.0.0.0 --port 8000

  # Production environment
  prod:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    image: qredenceai/agenticfleet:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
    restart: unless-stopped
    command: chainlit run src/agentic_fleet/app.py --host 0.0.0.0 --port 8000
