[project]
name = "agenticfleet"
version = "0.5.0"
description = "A multi-agent system built with Microsoft Agent Framework"
authors = [
    { name = "Qredence", email = "contact@qredence.ai" },
]
dependencies = [
    "agent-framework>=1.0.0b251007",
    "openai<=2.3.0",
    "python-dotenv>=1.0.0",
    "pyyaml>=6.0",
    "requests>=2.31.0",
    "pydantic>=2.0.0",
    "mem0ai==1.0.0b0",
]
requires-python = ">=3.12"

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
    "black>=24.0.0",
    "ruff>=0.1.0",
    "mypy>=1.8.0",
    "debugpy>=1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["config", "agents", "workflows", "tests"]

[tool.uv.sources]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
    "black>=24.0.0",
    "ruff>=0.1.0",
]

[tool.black]
target-version = ['py312']
line-length = 100

[tool.ruff]
target-version = "py312"
line-length = 100
select = [
    "E", "F", "W",  # basic codes
    "I",  # import sorting
    "UP",  # pyupgrade
]
ignore = []

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
