[project]
name = "agenticfleet"
version = "0.5.0"
description = "A multi-agent system built with Microsoft Agent Framework"
authors = [{ name = "Qredence", email = "contact@qredence.ai" }]
dependencies = [
    "azure-ai-agents>=1.2.0b5",
    "azure-identity>=1.25.1",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "pydantic>=2.12.0",
    "agent-framework",
    "agent-framework-core",
    "agent-framework-a2a",
    "agent-framework-azure-ai",
    "agent-framework-mem0",
    "agent-framework-redis",
    "agent-framework-devui",
    "mem0ai==1.0.0b0",
]
requires-python = ">=3.12"

[project.optional-dependencies]
dev = [
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "black>=25.9.0",
    "ruff>=0.14.0",
    "mypy>=1.18.2",
    "debugpy>=1.8.17",
]
azure = ["azure-ai-agents>=1.2.0b5"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["config", "agents", "workflows", "tests"]

[tool.uv.sources]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "black>=25.9.0",
    "ruff>=0.14.0",
]

[tool.black]
target-version = ['py312']
line-length = 100

[tool.ruff]
target-version = "py312"
line-length = 100
select = [
    "E",
    "F",
    "W",  # basic codes
    "I",  # import sorting
    "UP", # pyupgrade
]
ignore = []

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
