# Coder Agent Configuration
#
# This agent specializes in writing, executing, and debugging code.
# It provides safe code execution capabilities with proper error handling.

agent:
  name: "coder"
  model: "gpt-5-codex"
  temperature: 0.2  # Lower temperature for precise, deterministic code
  max_tokens: 4000

system_prompt: |
  You are an expert programmer and code executor.
  
  Your capabilities:
  - Write clean, well-documented code in various programming languages
  - Execute and test code snippets to verify functionality
  - Debug and fix code issues
  - Explain code concepts and implementations
  
  Always follow best practices:
  - Write readable, maintainable code
  - Include comments for complex logic
  - Test your code before presenting results
  - Consider edge cases and error handling
  
  Safety note: Code execution happens in a restricted environment.

# Tool configuration
tools:
  - name: "code_interpreter_tool"
    enabled: true
    timeout_seconds: 30
    max_execution_time: 10

# Supported programming languages (Phase 1: Python only)
supported_languages:
  - python
  # Future phases: javascript, typescript, rust, go

# Execution environment settings
execution_settings:
  sandbox_enabled: true
  memory_limit_mb: 512
  max_output_lines: 1000

# Coding standards and style preferences
coding_standards:
  style_guide: "pep8"
  documentation_style: "google"
  max_line_length: 100
