# Workflow-level configuration for AgenticFleet
workflow:
  max_rounds: 10
  max_stalls: 3
  max_resets: 2
  timeout_seconds: 300
  checkpointing:
    enabled: true
    storage_type: file  # Options: file, memory
    storage_path: ./checkpoints
    cleanup_after_days: 30
    auto_resume_on_failure: false
  human_in_the_loop:
    enabled: true
    approval_timeout_seconds: 300  # 5 minutes
    auto_reject_on_timeout: false
    require_approval_for:
      - code_execution
      - file_operations
      - external_api_calls
      - sensitive_data_access
    trusted_operations:
      - web_search
      - data_analysis

# Shared defaults that can be overridden by individual agents
defaults:
  model: "gpt-5"
  temperature: 0.2
  max_tokens: 4000
  top_p: 1.0
