providers:
  azure:
    name: "Azure OpenAI"
    config:
      api_version: "2024-12-01-preview"
      azure_deployment: "o3-mini"
    models:
      o3-mini:
        name: "o3-mini"
        context_length: 128000
        prompt_token_cost: 0.01
        completion_token_cost: 0.03
        vision: true
        function_calling: true
        json_output: true
        family: "azure"
        architecture: "o3-mini"
