receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 400
    spike_limit_mib: 100
  batch:
    timeout: 1s
    send_batch_size: 512

exporters:
  debug:
    verbosity: detailed
  file/local:
    path: var/observability/collector.log
    rotation:
      max_megabytes: 50
      max_backups: 3
extensions:
  health_check: {}

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, file/local]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, file/local]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, file/local]
