# Configuration for basic agent chat example

# Model settings
model:
  name: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 128000
  streaming: true

# Agent settings
agents:
  web_surfer:
    description: "Navigates and extracts information from the web"
    headless: true
    start_page: "https://www.bing.com"
    timeout: 300
    
  file_surfer:
    description: "Manages file operations and information extraction"
    allowed_extensions: [".txt", ".md", ".py", ".json", ".yaml", ".yml"]
    max_file_size: 10485760  # 10MB
    
  coder:
    description: "Generates and reviews code"
    supported_languages: ["python", "javascript", "typescript"]
    max_code_length: 5000
    
  executor:
    description: "Executes code safely in an isolated environment"
    timeout: 300
    max_memory: "512M"
    allowed_modules: ["os", "sys", "json", "yaml", "requests", "pandas", "numpy"]

# UI settings
ui:
  theme: "light"
  code_highlighting: true
  show_timestamps: true
  max_messages: 1000
  stream_delay: 0.03

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/agent_chat.log"
  max_size: 10485760  # 10MB
  backup_count: 5 