[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

[auth]
# Using OAuth
type = "oauth"

[project.oauth]
enabled = true
providers = ["github", "google"]
client_id = "OAUTH_GITHUB_CLIENT_ID"
client_secret = "OAUTH_GITHUB_CLIENT_SECRET"

[project.oauth.github]
prompt = "login"
consent = "consent"
redirect_uri = "http://localhost:8000/auth/oauth/github/callback"

[project.oauth.google]
prompt = "login"
consent = "consent"
client_id = "${OAUTH_GOOGLE_CLIENT_ID}"
client_secret = "${OAUTH_GOOGLE_CLIENT_SECRET}"
redirect_uri = "http://localhost:8000/auth/oauth/google/callback"

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Force consent prompt for all providers
OAUTH_PROMPT = "consent"

# Duration (in seconds) of the user session expiry
user_session_timeout = 1296000  # 15 days

# Enable third parties caching (e.g LangChain cache)
cache = false

# Authorized origins
allow_origins = ["http://localhost:8000"]

[features]
# Process and display HTML in messages
unsafe_allow_html = false

# Process and display mathematical expressions
latex = false

# Automatically tag threads with the current chat profile
auto_tag_thread = true

# Allow users to edit their own messages
edit_message = true

# Authorize users to spontaneously upload files with messages
[features.spontaneous_file_upload]
    enabled = true
    accept = ["*/*"]
    max_files = 20
    max_size_mb = 500

[features.audio]
    # Sample rate of the audio
    sample_rate = 24000

[UI]
# Name of the assistant.
name = "AgenticFleet"
description = "AI Agent Fleet Management"

default_theme = "light"
# Large size content are by default collapsed for a cleaner ui
default_collapse_content = false

# The default value for the expand messages settings.
default_expand_messages = true
layout = "wide" 

# Description of the assistant. This is used for HTML tags.
# description = ""

# Chain of Thought (CoT) display mode. Can be "hidden", "tool_call" or "full".
cot = "full"

# Link to your github repo. This will add a github button in the UI's header.
github = "https://github.com/Qredence/AgenticFleet"

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
custom_css = "/public/custom.css"

# Specify a Javascript file that can be used to customize the user interface.
# The Javascript file can be served from the public directory.
# custom_js = "/public/test.js"

# Specify a custom meta image url.
# custom_meta_image_url = "https://chainlit-cloud.s3.eu-west-3.amazonaws.com/logo/chainlit_banner.png"

# Specify a custom build directory for the frontend.
# This can be used to customize the frontend code.
# Be careful: If this is a relative path, it should not start with a slash.
# custom_build = "./public/build"

[meta]
generated_by = "2.2.0"

[server]
port = 8000
host = "localhost"
