[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true


[auth]
# Using OAuth
type = "oauth"

[project.oauth]
enabled = true
providers = ["github"]
client_id = "OAUTH_GITHUB_CLIENT_ID"
client_secret = "OAUTH_GITHUB_CLIENT_SECRET"

[project.oauth.github]
prompt = "login"
consent = "consent"
redirect_uri = "http://localhost:8000/auth/callback"
client_id = "OAUTH_GITHUB_CLIENT_ID"
client_secret = "OAUTH_GITHUB_CLIENT_SECRET"

# List of environment variables to be provided by each user to use the app.
user_env = []

[server]
port = 8000

[UI]
# Name of the app and chatbot.
name = "AgenticFleet"
# Description of the app and chatbot. This is used for HTML tags.
description = "AgenticFleet - Your AI Agent Fleet"

# The default value for the expand messages settings.
default_expand_messages = true

# Hide the chain of thought details from the user.
hide_cot = false
# Link to your github repo. This will add a github button in the UI's header.
github = "https://github.com/Qredence/AgenticFleet"

# Chain of Thought (CoT) display mode. Can be "hidden", "tool_call" or "full".
cot = "full"
tool_call = "full"

# Specify a CSS file that can be used to customize the user interface.
custom_css = "/public/custom.css"
custom_theme = "/public/theme.json"


# Override default MUI light theme. (Check theme.ts)

[features]
# Show the prompt playground.
prompt_playground = true
display_chat_history = true

# Enable multi-modal inputs (audio, video, images).
multi_modal = true
# Enable speech recognition.
speech_to_text = false
# Enable file upload.
file_upload = true
# Enable user settings.
user_settings = true

# Enable citations.
citations = true

# Enable code execution.
code_execution = true

# Enable human feedback collection.
human_feedback = true

# Enable chat profiles.
chat_profiles = true

# Enable custom elements.
custom_elements = true

# Enable data streaming.
streaming = true

# Enable ask user interactions.
ask_user = true
# Enable data persistence.
data_persistence = true


transports = ["websocket"]

[features.spontaneous_file_upload]
    enabled = true
    accept = ["image/*", "audio/*", "video/*"]
    max_files = 20
    max_size_mb = 500

[features.audio]
    # Sample rate of the audio
    sample_rate = 24000
auto_tag_thread = true





# GitHub OAuth provider
[[oauth.providers]]
name = "github"
client_id = "OAUTH_GITHUB_CLIENT_ID"
client_secret = "OAUTH_GITHUB_CLIENT_SECRET"
authorize_url = "https://github.com/login/oauth/authorize"
access_token_url = "https://github.com/login/oauth/access_token"
userinfo_url = "https://api.github.com/user"
scope = ["user:email"]

[meta]
generated_by = "2.2.1"
generated_from = "chainlit"
generated_from_version = "2.2.1"

