[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

[auth]
# Using OAuth
type = "oauth"

[project.oauth]
enabled = true
providers = ["github"]
client_id = "OAUTH_GITHUB_CLIENT_ID"
client_secret = "OAUTH_GITHUB_CLIENT_SECRET"

[project.oauth.github]
prompt = "login"
consent = "consent"
redirect_uri = "http://localhost:8000/auth/callback"
client_id = "OAUTH_GITHUB_CLIENT_ID"
client_secret = "OAUTH_GITHUB_CLIENT_SECRET"

# List of environment variables to be provided by each user to use the app.
user_env = []


[features.spontaneous_file_upload]
    enabled = true
    accept = ["*/*"]
    max_files = 20
    max_size_mb = 500
auto_tag_thread = true

[UI]
# Name of the app and chatbot.
name = "AgenticFleet"
# Description of the app and chatbot.
description = "A multi-agent system for adaptive AI reasoning"
# The default value for the expand messages settings.
default_expand_messages = false
# Hide the chain of thought details from the user.
hide_cot = false
# Enable dark mode.
dark_mode = true
# Show the copy button on messages.
show_copy_button = true
custom_css = "public/css/custom.css"


[features]
# Enable the multi-modal file upload feature.
multi_modal = true
# Enable the speech to text feature.
speech_to_text = false
# Enable the file Q&A feature.
file_qa = true
edit_message = true
unsafe_allow_html = false
latex = false

[oauth]
# Enable OAuth web application flow.
enable_oauth = true

# GitHub OAuth provider
[[oauth.providers]]
name = "github"
client_id = "OAUTH_GITHUB_CLIENT_ID"
client_secret = "OAUTH_GITHUB_CLIENT_SECRET"
authorize_url = "https://github.com/login/oauth/authorize"
access_token_url = "https://github.com/login/oauth/access_token"
userinfo_url = "https://api.github.com/user"
scope = ["user:email"]

[meta]
generated_by = "AgenticFleet"
version = "0.4.80"
