name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Set up virtual environment
      run: uv venv

    - name: Install dependencies
      run: |
        . .venv/bin/activate
        uv pip install -r src/backend/pyproject.toml -r src/frontend/requirements.txt

    - name: Run tests
      run: |
        . .venv/bin/activate
        pytest src/backend/test
